server:
  port: 8085

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vikas054/hotel-microservice-configuration
          clone-on-start: true

